

const asyncHandler = require('express-async-handler');
const bcrypt = require('bcryptjs');
const BrokerModel = require('../Model/BrokerModel'); 


const getBrokers = asyncHandler(async (req, res) => {
    // MongoDB se saare documents fetch karein jinka role 'broker' hai
    const brokers = await BrokerModel.find({ role: 'broker' }).select('-hashed_password'); // Security ke liye password remove kiya

    // Data ko frontend table ke format mein taiyar karein
    const formattedBrokers = brokers.map(broker => ({
        // Login ID: Mongoose ki default _id nahi, balki 10-digit login_id use hogi
        id: broker.login_id, 
        name: broker.name,
        joining_date: broker.createdAt ? broker.createdAt.toISOString().split('T')[0] : 'N/A',
        status: 'Active', // Ya aapki zaroorat ke mutabik koi aur status field
    }));

    res.status(200).json({
        success: true,
        brokers: formattedBrokers,
        count: brokers.length,
    });
});

// Note: Yeh function CustomerController.js mein hoga aur addBrokerPublic ke saath export hoga.
// module.exports = { getBrokers, addBrokerPublic, ... };


// Yeh code ab aapke `BrokerDetailsPage.jsx` ki zarurat ke mutabik **sabhi Brokers** ka data fetch karega aur frontend ke liye required format mein bhej dega.

// Kya aapko **`addBrokerPublic`** function ka code bhi chahiye jismein **`BrokerModel`** ka use ho raha ho?

const addBroker = asyncHandler(async (req, res) => {
    // AddBrokerModal se sirf name aur password aayega
    const { name, password } = req.body; 
    console.log("api hit")

    if (!name || !password) {
        res.status(400).json({ success: false, message: 'Kripya naam aur password daalein.' });
        return;
    }

    // Hash Password
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(password, salt);

    // Create New Broker (login_id is auto-generated by the model)
    const newBroker = await BrokerModel.create({
        name,
        hashed_password: hashedPassword,
    });

    if (newBroker) {
        res.status(201).json({
            success: true,
            message: 'Naya Broker successfully add ho gaya.',
            newBroker: {
                id: newBroker.login_id, // Return the auto-generated 10-digit ID
                name: newBroker.name,
                status: 'Active',
                joining_date: newBroker.created_at.toISOString().split('T')[0]
            },
        });
    } else {
        res.status(400).json({ success: false, message: 'Broker data invalid hai.' });
    }
});


module.exports = {
    getBrokers,
    addBroker,
};