import asyncHandler from 'express-async-handler';
import BrokerModel from '../Model/BrokerModel.js';

const getBrokers = asyncHandler(async (req, res) => {
   
    const brokers = await BrokerModel.find({ role: 'broker' }).select('-password'); 
    
 
    const formattedBrokers = brokers.map(broker => ({
        
        id: broker.login_id, 
        name: broker.name,
        password: broker.password,
        joining_date: broker.createdAt ? broker.createdAt.toISOString().split('T')[0] : 'N/A',
        status: 'Active',
    }));

    console.log(formattedBrokers)

    res.status(200).json({
        success: true,
        brokers: formattedBrokers,
        count: brokers.length,
    });
});



const addBroker = asyncHandler(async (req, res) => {
    // AddBrokerModal se sirf name aur password aayega
    const { name, password } = req.body; 
    console.log("api hit")

    if (!name || !password) {
        res.status(400).json({ success: false, message: 'Kripya naam aur password daalein.' });
        return;
    }

    // Create New Broker (login_id is auto-generated by the model)
    // Password stored as plain text
    const newBroker = await BrokerModel.create({
        name,
        password: Number(password),
    });

    if (newBroker) {
        res.status(201).json({
            success: true,
            message: 'new Broker added successfully.',
            newBroker: {
                id: newBroker.login_id, // Return the auto-generated 10-digit ID
                name: newBroker.name,
                password : password,
                status: 'Active',
                joining_date: newBroker.created_at.toISOString().split('T')[0]
            },
        });
    } else {
        res.status(400).json({ success: false, message: 'Broker data invalid hai.' });
    }
});

export { addBroker, getBrokers };