const mongoose = require('mongoose');
const { Schema } = mongoose;

// Helper function to generate a unique 10-digit ID
function generateId() {
    // Generates a 10-digit number between 1,000,000,000 and 9,999,999,999
    return Math.floor(1000000000 + Math.random() * 9000000000).toString();
}

const CustomerSchema = new Schema({
    // 🔑 PRIMARY LOGIN IDENTIFIER: Customer ID (10 Digits)
    customer_id: {
        type: String,
        required: true,
        unique: true,
        default: generateId, // ID will be auto-generated by the model
    },
    
    hashed_password: {
        type: String,
        required: true,
    },
    
    name: {
        type: String,
        required: true,
    },
    
    // Role fixed hai
    role: {
        type: String,
        default: 'customer',
        immutable: true,
    },
    
    // 🔗 BROKER LINKAGE: Broker Model ko reference karega
    attached_broker_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Broker', // Yeh field 'Broker' collection (Model) ko point karegi
        required: true, // Customer hamesha kisi Broker se attached hoga
    },

    // NOTE: 'timestamps: true' set hai, jo automatic 'createdAt' aur 'updatedAt' field banata hai.
}, { timestamps: true }); // <--- Yeh 'createdAt' field provide karega

module.exports = mongoose.model('Customer', CustomerSchema);
